version: "3.3"
services:

  prometheus:
    image: prom/prometheus:v2.17.2
    ports:
      - "9090:9090"
    networks:
      - frontend
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  frontend:
